### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Made101** [yaldabaoth444/Asphalt9#3] opened 2021-05-19 20:18 UTC
Can you make the script press brake button for 3-4 seconds after tapping n number of times on nitro. Just to make it more look like a real player.

**Comment by Made101** [comment] 2021-05-19 20:28
@yaldabaoth444 also in MP2, They give us only 8 cars, in which 6 of them are at the end and the script is not able to select the car because the screen cannot be swiped further and it sends error that the car doesn't have the fuel even when it has fuel. 
I'll link a screenshot as an example


![Screenshot_20210520-014941_dac78dbb8b9d35e2ecbeaf4ec6ecff5b__01](https://user-images.githubusercontent.com/77076813/118879591-88c19200-b90e-11eb-99fc-409cd23bf916.jpg)
 
Can you design a different fuel selection function specifically for this type of MP2?

**Comment by yaldabaoth444** [comment] 2021-05-19 21:05
Added a parameter to the function of pressing the brake.
![image](https://user-images.githubusercontent.com/25618671/118883996-595f5500-b90f-11eb-9e0f-b146af67dbf6.png)
P.S. ..this press on the brake was used (in hunting mode) with the aspphalt.9.mod to fill nitro ;)

**Comment by yaldabaoth444** [comment] 2021-05-19 21:17
Adding a new selection mode is also possible, did not do so for reasons of infrequent use and limited options (only 6 cars)
...if we exclude swipes

**Comment by Made101** [comment] 2021-05-19 21:27
> Adding a new selection mode is also possible, did not do so for reasons of infrequent use and limited options (only 6 cars)
> ...if we exclude swipes

I think it's only needed for Mp2. Not for Mp1. Mp2 will be here after a day. So, just wanted to hear your thoughts on it.
One swipe is needed in Mp2, If we get 8 cars but the first 2 cars can be selected by the regular fuel check method but the other 6 cannot. That's why, After fuel of car(1,2) is over, the script should swipe once and then check for fuel for the cars(3,4,5,6,7,8). I think we should wait till the Mp2 comes to see what cars have.

**Comment by Made101** [comment] 2021-05-19 21:31
> Added a parameter to the function of pressing the brake.
> ![image](https://user-images.githubusercontent.com/25618671/118883996-595f5500-b90f-11eb-9e0f-b146af67dbf6.png)
> P.S. ..this press on the brake was used (in hunting mode) with the aspphalt.9.mod to fill nitro ;)

I'll add this to the multiplayer one. Thank you very much. :)

**Comment by yaldabaoth444** [comment] 2021-05-19 21:54
In my opinion, random braking worsens the result, although it may help not to crash

**Comment by Made101** [comment] 2021-05-19 21:56
> In my opinion, random braking worsens the result, although it may help not to crash

It does. But it helps mask the script. Otherwise people would be too suspicious.

**Comment by yaldabaoth444** [comment] 2021-05-19 22:08
route selection can be added, but you have to make screenshots like this 
![image](https://user-images.githubusercontent.com/25618671/118890674-88c68f80-b918-11eb-9ba9-10d68dde9c6c.png)
We need to think about it

**Comment by yaldabaoth444** [comment] 2021-05-19 22:10
rhythmic pressure on the brake is also suspicious

**Comment by Made101** [comment] 2021-05-19 22:17
> route selection can be added, but you have to make screenshots like this
> ![image](https://user-images.githubusercontent.com/25618671/118890674-88c68f80-b918-11eb-9ba9-10d68dde9c6c.png)
> We need to think about it

I don't think we need route selection or map detection, It'll be too much work to fix if there's an error but it'll be a lot better. And yeah the rythmic pressure is suspicious, you'll have to make it like it has to press brake after random number of Nitro taps. One after 5 then 10 then 15 then again 5.

**Comment by Made101** [comment] 2021-05-19 22:18
> route selection can be added, but you have to make screenshots like this
> ![image](https://user-images.githubusercontent.com/25618671/118890674-88c68f80-b918-11eb-9ba9-10d68dde9c6c.png)
> We need to think about it

And I also think If you add route selection then you don't need the drift option. But you'll have to make it like it only selects ramp, nitro bottles I think are not necessary.

**Comment by yaldabaoth444** [comment] 2021-05-19 22:19
you can try this `brkc = Math.floor(Math.random() * 10);`

**Comment by yaldabaoth444** [comment] 2021-05-19 22:20
yes that's right, it shows good results in the windows version

**Comment by yaldabaoth444** [comment] 2021-05-19 22:21
> > route selection can be added, but you have to make screenshots like this
> > ![image](https://user-images.githubusercontent.com/25618671/118890674-88c68f80-b918-11eb-9ba9-10d68dde9c6c.png)
> > We need to think about it
> 
> And I also think If you add route selection then you don't need the drift option. But you'll have to make it like it only selects ramp, nitro bottles I think are not necessary.

yes that's right, it shows good results in the windows version

**Comment by yaldabaoth444** [comment] 2021-05-19 22:31
I'll get to it when the hunt is over. 34 hours to go, and I have 54 Roma cards to collect. :)

**Comment by made101** [comment] 2021-05-19 23:10
Good luck man. I'm only at 2 stars haha. Didn't play the hunt too much. :)

> I'll get to it when the hunt is over. 34 hours to go, and I have 54 Roma cards to collect. :)

**Comment by yaldabaoth444** [comment] 2021-05-20 05:35
collects tickets up to 10 (if there are no ads then reset), then hunt 5 times, and then all over again. Just not sure if the algorithm should be posted in the public

**Comment by made101** [comment] 2021-05-20 05:43
> collects tickets up to 10 (if there are no ads then reset), then hunt 5 times, and then all over again. Just not sure if the algorithm should be posted in the public. ...the reset procedure requires universalization

The reset meaning, closing the window where the skip duration shows? I also think, we can only collect up to 12-14 tickets per day with ads.

**Comment by yaldabaoth444** [comment] 2021-05-20 05:57
no it means resetting the app data after which the ads are restored ;)

**Comment by made101** [comment] 2021-05-20 05:59
> no it means resetting the app data after which the ads are restored ;)

Does this mean unlimited ads?

**Comment by made101** [comment] 2021-05-20 06:03
> no it means resetting the app data after which the ads are restored ;)

OH. I understood now.

**Comment by yaldabaoth444** [comment] 2021-05-20 06:04
yep

**Comment by made101** [comment] 2021-05-20 06:05
How much trial and error will it take to universalize this?

**Comment by yaldabaoth444** [comment] 2021-05-20 06:10
this code is already present in the RestartWithReset function, there are many custom coordinates that I customized, not sure if this will work for other users

**Comment by yaldabaoth444** [comment] 2021-05-20 06:11
Try reinstalling the game and see how many manipulations it takes to get into the game

**Comment by made101** [comment] 2021-05-20 06:19
> this code is already present in the RestartWithReset function, there are many custom coordinates that I customized, not sure if this will work for other users


The function or the method?

**Comment by yaldabaoth444** [comment] 2021-05-20 06:21
last function in play.js

**Comment by made101** [comment] 2021-05-20 06:23
> Try reinstalling the game and see how many manipulations it takes to get into the game

I'll try customizing it now. In the appname, I have to put Asphalt 9 and what do I have to do to test it?

**Comment by made101** [comment] 2021-05-20 06:25
> last function in play.js

What values do I have to change to specifically only check that function?

**Comment by yaldabaoth444** [comment] 2021-05-20 06:27
![image](https://user-images.githubusercontent.com/25618671/118929767-6192b100-b95e-11eb-9016-97e917a4e5fa.png)
something like this

**Comment by yaldabaoth444** [comment] 2021-05-20 06:38
you need to be careful when using this function too often, there is a possibility of ban from the GL

**Comment by made101** [comment] 2021-05-20 06:41
> you need to be careful when using this function too often, there is a possibility of ban from the GL

2 or 3 times in 2 days is good?

**Comment by made101** [comment] 2021-05-20 06:58
@yaldabaoth444 
![Screenshot_20210520-122523](https://user-images.githubusercontent.com/77076813/118933202-8c810300-b966-11eb-909a-7ededcf52cfa.jpg)

I have a OnePlus 6t so these are the co ordinates I changed to. I change the 'close' and 'ok'. 
What are the 'clear' and 'clear all' are used in this situation?

**Comment by yaldabaoth444** [comment] 2021-05-20 07:04
![image](https://user-images.githubusercontent.com/25618671/118934211-8a697500-b963-11eb-8988-00d6a08412a3.png)

**Comment by made101** [comment] 2021-05-20 07:06
Is clear all neccessary to do? It removes the obb file.

**Comment by yaldabaoth444** [comment] 2021-05-20 07:08
Clean data, not just the cache.
obb files at the time of reset are in the renamed folder, see shell command

**Comment by made101** [comment] 2021-05-20 07:09
Oh. I get it now.

**Comment by made101** [comment] 2021-05-20 07:10
Re-downloading and making the script re-login all by itself. I understand now.

**Comment by made101** [comment] 2021-05-20 07:11
Also, did you put up a function of refueling tickets by clicking on ads? How do I enable that?

**Comment by made101** [comment] 2021-05-20 07:15
> Clean data, not just the cache.
> obb files at the time of reset are in the renamed folder, see shell command (1259 line)
> and return to their place with the shell command on line 1274
> Otherwise you will have to reload 2gb of data

Okay

**Comment by made101** [comment] 2021-05-20 07:19
> Give me your email, I'll send you the file

altamashamilsh6@gmail.com

**Comment by yaldabaoth444** [comment] 2021-05-20 07:25
it's hard to send the script, the fuc*ing security system...texted it in

**Comment by yaldabaoth444** [comment] 2021-05-20 07:33
I took consecutive screenshots and then entered the clicks into the script, with the possible delay between clicks (different screens)
..true - requires root privileges (it seems)

**Comment by yaldabaoth444** [comment] 2021-05-20 07:34
got the email?

**Comment by made101** [comment] 2021-05-20 07:37
> got the email?

I don't see it.

**Comment by made101** [comment] 2021-05-20 07:38
> I took consecutive screenshots and then entered the clicks into the script, with the possible delay between clicks (different screens)
> ..true - requires root privileges (it seems)

I get stuck at the safe cache.

**Comment by yaldabaoth444** [comment] 2021-05-20 07:39
https://drive.google.com/file/d/1MJEHAfTvaj3poOf4VaTsAdkhZ8C2_FO5/view?usp=sharing (3 min alive) Let me know when you've downloaded it.

**Comment by made101** [comment] 2021-05-20 07:40
> https://drive.google.com/file/d/1MJEHAfTvaj3poOf4VaTsAdkhZ8C2_FO5/view?usp=sharing (3 min alive) Let me know when you've downloaded it.

done

**Comment by made101** [comment] 2021-05-20 07:42
I'll root and try again and will tell you the results in an hour.

**Comment by yaldabaoth444** [comment] 2021-05-20 07:43
Samsung and Huawei versions are located in different folders, you need to check the path to the obb files
![image](https://user-images.githubusercontent.com/25618671/118939301-f69aa780-b968-11eb-83e4-0fcea04cfcdf.png)

**Comment by yaldabaoth444** [comment] 2021-05-20 07:45
and shell commands work for me

**Comment by made101** [comment] 2021-05-20 07:47
> Samsung and Huawei versions are located in different folders, you need to check the path to the obb files
> ![image](https://user-images.githubusercontent.com/25618671/118939301-f69aa780-b968-11eb-83e4-0fcea04cfcdf.png)

Yeah, this is the issue. That's the address where the obb is in my phone

**Comment by made101** [comment] 2021-05-20 07:48
I'll run and tell you the results in 10-15 minutes.

**Comment by made101** [comment] 2021-05-20 07:56
> ![image](https://user-images.githubusercontent.com/25618671/118940029-be479900-b969-11eb-89e5-c1655272f941.png)
> same folder

![Screenshot_20210520-132453__01](https://user-images.githubusercontent.com/77076813/118940981-e5549980-b96e-11eb-9bd6-69048006b999.jpg)

Mine is just like yours but still having quite some problems.

**Comment by yaldabaoth444** [comment] 2021-05-20 08:55
What kind of problems?
..run the shell commands separately and see if the directory has changed.

**Comment by made101** [comment] 2021-05-20 09:15
> What kind of problems?
> ..run the shell commands separately and see if the directory has changed.

![Screenshot_20210520-144406](https://user-images.githubusercontent.com/77076813/118952931-fce54f80-b979-11eb-9127-8f544bd6c56d.jpg)

This came up.

**Comment by made101** [comment] 2021-05-20 09:18
![Screenshot_20210520-144742](https://user-images.githubusercontent.com/77076813/118953383-64030400-b97a-11eb-8375-a4b973cda960.jpg)

Would this be causing it?

**Comment by yaldabaoth444** [comment] 2021-05-20 09:30
android version?

**Comment by yaldabaoth444** [comment] 2021-05-20 09:39
Does it let you rename the directory manually?
it is not clear whether the problem is with the command or the directory

**Comment by made101** [comment] 2021-05-20 09:46
> android version?

10.

**Comment by made101** [comment] 2021-05-20 09:47
> Does it let you rename the directory manually?
> it is not clear whether the problem is with the command or the directory

I'm rooting the device now and will try again once the phone is ready.

**Comment by made101** [comment] 2021-05-20 10:51
Solved it. It needed root to work.

**Comment by yaldabaoth444** [comment] 2021-05-20 10:54
hmm ok

**Comment by made101** [comment] 2021-05-20 11:00
> hmm ok

You need the values I changed? or should I keep it to myself?

**Comment by yaldabaoth444** [comment] 2021-05-20 11:02
It's interesting to see

**Comment by made101** [comment] 2021-05-20 11:15
> It's interesting to see

![Screenshot (89)](https://user-images.githubusercontent.com/77076813/118969447-b4825d80-b98a-11eb-8521-d5164eb5572b.png)
![Screenshot (90)](https://user-images.githubusercontent.com/77076813/118969459-b77d4e00-b98a-11eb-82ff-96cd5496e4f2.png)

These are the values I changed.

**Comment by yaldabaoth444** [comment] 2021-05-20 11:23
Okay, I think this process is too individual and depends on the differences in the UI

**Comment by Made101** [comment] 2021-05-20 11:25
> Did it work after rooting?

It did perfectly.

**Comment by Made101** [comment] 2021-05-20 11:26
> Did it work after rooting?

I'm also having a problem in car selection of flat mode, I'm changing the value of first car and will tell you how it goes.

**Comment by Made101** [comment] 2021-05-20 12:11
hey, I tried but the problem still persists. Can you check if it's working for you?

**Comment by yaldabaoth444** [comment] 2021-05-20 12:15
What exactly? flat mode?

**Comment by Made101** [comment] 2021-05-20 12:17
> What exactly? flat mode?

Yeah. Ordinary is working fine. Only flat mode seems to be not working.

**Comment by yaldabaoth444** [comment] 2021-05-20 12:21
at the moment I have hunting in flat mode and everything is ok

**Comment by Made101** [comment] 2021-05-20 12:22
> at the moment I have hunting in flat mode and everything is ok

Everything is working now. I replaced the profile2340.js with the one you provided here and now everything's working fine.

**Comment by yaldabaoth444** [comment] 2021-05-20 12:27
ok

**Comment by yaldabaoth444** [comment] 2021-05-20 12:28
you can run HUNT.adjustSwipe(20, 1500) to check (see https://github.com/yaldabaoth444/Asphalt9/issues/1)

**Comment by Made101** [comment] 2021-05-20 12:29
> you can run HUNT.adjustSwipe(20, 1500) to check (see #1)

Okay. I'll try that after the hunt is completed and tell you if anything goes wrong on my side.

**Comment by yaldabaoth444** [comment] 2021-05-20 12:51
I think it was because the AdCloserFolder: './AdCloser/' option was missing, I added it to cope with the abundance of ads in which the close buttons are in different places

**Comment by Made101** [comment] 2021-05-20 12:55
> I think it was because the AdCloserFolder: './AdCloser/' option was missing, I added it to cope with the abundance of ads in which the close buttons are in different places

Okay. But the funny thing is the ads you get are different because of our locations. So, now I'm using a VPN for that. haha.

**Comment by Made101** [comment] 2021-05-20 12:58
Also, how can I modify the script to be suitable to my ads? To make the script click on the cross buttons of my ads.

**Comment by made101** [comment] 2021-05-20 13:05
I'm getting more ads which have this type of cross button on the top right.
![Screenshot_20210520-183327_dac78dbb8b9d35e2ecbeaf4ec6ecff5b__01](https://user-images.githubusercontent.com/77076813/118983512-2615d800-b99a-11eb-951f-399ecf3741a0.jpg)

**Comment by Made101** [comment] 2021-05-20 13:09
I'll try and change location and try to get similar ads to yours.

**Comment by Made101** [comment] 2021-05-20 13:16
I've set the location to belarus, Let's see what happens.

**Comment by yaldabaoth444** [comment] 2021-05-20 14:32
all crosses are the same :)

**Comment by yaldabaoth444** [comment] 2021-05-20 14:34
Check this directory
![image](https://user-images.githubusercontent.com/25618671/118997787-5a8d9200-b9a2-11eb-90b4-2e2387d302a6.png)
you can delete everything and replace it with your own
file names do not matter

**Comment by yaldabaoth444** [comment] 2021-05-20 14:45
I haven't had a chance to play with the parameters yet
you can add an option that will improve the degree of recognition

1170: var pos = images.findImage(imgad, template);

var pos = images.findImage(imgad, template, {threshold: 0.8});

**Comment by Made101** [comment] 2021-05-21 02:29
Hey, I had problems yesterday as the flat fuel check method failed to work several times on my rooted device but as soon as I unrooted it, It started working. Do you know what could be causing it? Smallest width was 392 in both cases.

**Comment by yaldabaoth444** [comment] 2021-05-21 04:18
maybe the rooted device is slower and you need to adjust the delta, run the adjustSwipe function

**Comment by yaldabaoth444** [comment] 2021-05-21 04:34
The swipe itself consists of a given distance and time for which the finger passes it, and this action has an inertia. The area being moved stops with a deceleration. This is influenced by some other unknown factors, such as CPU power, UI settings, etc.

**Comment by Made101** [comment] 2021-05-21 09:25
[](url)

> The swipe itself consists of a given distance and time for which the finger passes it, and this action has an inertia. The area being moved stops with a deceleration. This is influenced by some other unknown factors, such as CPU power, UI settings, etc.

I changed the swipe duration to 2000 and 3000 but still error persists. Only thing I notice was with each swipe it moves a bit further which would be negligible when I was unrooted. The ordinary mode still works fine for now. also, the script stuck at the end is not a problem, it happens when I try to record fuel selection

Can you please check this video and guide me through this?
[Fuelcheck](https://youtu.be/5pclFY7C9hM)
also, where is the delta located? 


I also wanted to know how do you mark the co-ordinates so accurately.

**Comment by yaldabaoth444** [comment] 2021-05-21 09:31
![image](https://user-images.githubusercontent.com/25618671/119115949-303ee180-ba41-11eb-9dd1-ca34846ac552.png)
you need to reduce this virtual delta :) by 1-2 pixels

**Comment by Made101** [comment] 2021-05-21 10:05
> ![image](https://user-images.githubusercontent.com/25618671/119115949-303ee180-ba41-11eb-9dd1-ca34846ac552.png)
> you need to reduce this virtual delta :) by 1-2 pixels

Thank you very much. :)
Previously I also changed it to 26 but it didn't work so I thought problem must be in the swipe duration but now when I changed it to 25, it works. Thank you so much :))

**Comment by Made101** [comment] 2021-05-21 10:08
If you don't mind, I also wanted to know how do you mark the co-ordinates so accurately.

**Comment by Made101** [comment] 2021-05-21 10:12
![Screenshot_20210521-154047_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/119121407-012d6d80-ba4b-11eb-836d-d1e348452515.jpg)
![Screenshot_20210521-154257_dac78dbb8b9d35e2ecbeaf4ec6ecff5b](https://user-images.githubusercontent.com/77076813/119121638-4782cc80-ba4b-11eb-9662-1715d390afc1.jpg)

This was the type of Mp2 I was suggesting about when I opened this suggestion.
Can you design a new fuel check specifically for this MP2?

**Comment by yaldabaoth444** [comment] 2021-05-21 10:21
![image](https://user-images.githubusercontent.com/25618671/119122627-24a2e900-ba48-11eb-8881-b772c653d3a0.png)

**Comment by Made101** [comment] 2021-05-21 10:25
Thank you so much for this :)))

**Comment by yaldabaoth444** [comment] 2021-05-21 10:25
If you use the ordinary mode in the MP2, only the last three cars drop out

**Comment by Made101** [comment] 2021-05-21 10:29
> If you use the ordinary mode in the MP2, only the last three cars drop out

Yeah, but last three can get first positions easily which will help in REPs and also milestones.
If you can then please do because more of these type of MP2s will comeout in future.

**Comment by yaldabaoth444** [comment] 2021-05-21 10:32
We'll figure something out.

**Comment by Made101** [comment] 2021-05-21 12:32
> We'll figure something out.

Thank you.
Also, If you are able to add selection of ramps also then please do so :)))

**Comment by yaldabaoth444** [comment] 2021-05-21 12:55
Yes, that's the first thing

**Comment by made101** [comment] 2021-05-21 18:58
Today, The only problem I faced was in ordinary mode now, but when I deleted the file and then transferred the same file from download folder, it started working again. Which would never happen before. I think I need to see how to change the user permissions for the mnt folder in my device and use it without rooting.

**Comment by Made101** [comment] 2021-05-23 14:14
Hey, I tried the script you updated and everything is working perfectly well.
Also, If I wanted to add nitro selection, I'd just to have to follow the same process as I did in Adcloser right?
Thank you for the script :))

**Comment by made101** [comment] 2021-05-23 14:19
Oh. I understood it, Nevermind.

**Comment by yaldabaoth444** [comment] 2021-05-23 15:12
You mean the nitro bottle selection?

**Comment by yaldabaoth444** [comment] 2021-05-23 15:14
Just put the picture 
![image](https://user-images.githubusercontent.com/25618671/119266286-9bd0ac80-bc03-11eb-8080-e9b32d790760.png)
 in directory TrafficSigns

**Comment by Made101** [comment] 2021-05-23 15:37
> Just put the picture
> ![image](https://user-images.githubusercontent.com/25618671/119266286-9bd0ac80-bc03-11eb-8080-e9b32d790760.png)
> in directory TrafficSigns

Yes. Thank you

**Comment by made101** [comment] 2021-05-23 16:54
Hey, I also got an error that the !closer is not defined. Also, I wanted to know, do I have to make an Adcloser2 with images of OK buttons? I wasn't able to find the Adcloser 2 folder.

**Comment by made101** [comment] 2021-05-23 16:54
I used the old method when I got this

**Comment by yaldabaoth444** [comment] 2021-05-23 17:07
This is only used during a reset, it is not public, so it is not in the repository

**Comment by made101** [comment] 2021-05-23 17:09
> This is only used during a reset, it is not public, so it is not in the repository

Oh, I understood that. So, will it be okay if I use the old method? Or to do this, I have to do the same procedure, you did with the First Ad folder but it'd be with okay buttons?

**Comment by yaldabaoth444** [comment] 2021-05-23 17:09
it is used to close the pop-up event ad when you first start the game after resetting

**Comment by Made101** [comment] 2021-05-23 17:10
> it is used to close the pop-up event ad when you first start the game after resetting

Okay. Thank you. Just wanted to confirm this.

**Comment by Made101** [comment] 2021-05-23 17:10
I got confused, if it was for some other purpose.

**Comment by yaldabaoth444** [comment] 2021-05-23 17:12
if called outside the play module, then via AdCloser, if inside, then the method is renamed to ImageClicker
![image](https://user-images.githubusercontent.com/25618671/119270004-f5d96e00-bc13-11eb-8883-d578768fe21c.png)

**Comment by made101** [comment] 2021-05-23 17:14
> if called outside the play module, then via AdCloser, if inside, then the method is renamed to ImageClicker
> ![image](https://user-images.githubusercontent.com/25618671/119270004-f5d96e00-bc13-11eb-8883-d578768fe21c.png)

Okay. I understood now. Thank you :)

**Comment by Made101** [comment] 2021-05-23 17:14
> > if called outside the play module, then via AdCloser, if inside, then the method is renamed to ImageClicker
> > ![image](https://user-images.githubusercontent.com/25618671/119270004-f5d96e00-bc13-11eb-8883-d578768fe21c.png)
> 

Okay. This is better Thank you :)

**Comment by yaldabaoth444** [comment] 2021-05-23 17:15
ImageClicker clicks on the picture found among the given directory and returns true if there was a match/click and false if not

**Comment by yaldabaoth444** [comment] 2021-05-23 17:17
this works both with closing ads and route selection, and can also be used for other purposes in the future

**Comment by Made101** [comment] 2021-05-23 17:19
> ImageClicker clicks on the picture found among the given directory and returns true if there was a match/click and false if not

Earlier, in the first folder, I faced an issue when I tried to learn how this functions. the script was unable to find the buttons but then I Looked at the profile.js and I found that I put the wrong location of the folder. Now, it's all good.

**Comment by yaldabaoth444** [comment] 2021-05-23 17:20
nice

**Comment by made101** [comment] 2021-05-23 18:53
> nice

![Screenshot (4)](https://user-images.githubusercontent.com/77076813/119272935-2924f880-bc26-11eb-8fbd-0003a9251054.png)

Just wanted to let you know the changes I made. Added back for the club status.

**Comment by Made101** [comment] 2021-05-23 19:48
>ImageClicker clicks on the picture found among the given directory and returns true if there was a match/click and false if not

Hey. These are the final changes. Now, everything works perfectly well.
![Screenshot (6)](https://user-images.githubusercontent.com/77076813/119274513-e6ffb500-bc2d-11eb-80d9-8c40b78998d5.png)

**Comment by yaldabaoth444** [comment] 2021-05-23 21:37
In my case, information about the event that requires scrolling pops up, so I customized the loop. In any case, your experience may also be useful.

**Comment by yaldabaoth444** [comment] 2021-05-23 21:38
this part changes from event to event

**Comment by yaldabaoth444** [comment] 2021-05-24 04:36
this is a separate auto set for slipstream mode :)
![image](https://user-images.githubusercontent.com/25618671/119296930-5c41a900-bc73-11eb-9a7d-56e677271b71.png)

**Comment by Made101** [comment] 2021-05-24 05:02
> In my case, information about the event that requires scrolling pops up, so I customized the loop. In any case, your experience may also be useful.

It was missing the OK image to click at first because the script kept scrolling, So, I had changed to this.

**Comment by Made101** [comment] 2021-05-24 05:02
> this is a separate auto set for slipstream mode :)
> ![image](https://user-images.githubusercontent.com/25618671/119296930-5c41a900-bc73-11eb-9a7d-56e677271b71.png)

Okay :)

**Comment by made101** [comment] 2021-05-24 06:12
> In my case, information about the event that requires scrolling pops up, so I customized the loop. In any case, your experience may also be useful.

Also. This swipe function was enough on my side for the script to scroll all the way to the OK button. That's why I removed the extra swipe.
![Screenshot (6)](https://user-images.githubusercontent.com/77076813/119304624-24dbf800-bc85-11eb-909e-60ae0af934bd.png)

**Comment by made101** [comment] 2021-05-24 06:13
> In my case, information about the event that requires scrolling pops up, so I customized the loop. In any case, your experience may also be useful.

Also. This swipe function was enough on my side for the script to scroll all the way to the OK button. That's why I removed the extra swipe.

**Comment by Made101** [comment] 2021-05-24 06:13
> In my case, information about the event that requires scrolling pops up, so I customized the loop. In any case, your experience may also be useful.

Also. This swipe function was enough on my side for the script to scroll all the way to the OK button. That's why I removed the extra swipe.


![Screenshot (7)](https://user-images.githubusercontent.com/77076813/119304721-4d63f200-bc85-11eb-802f-415801fd5823.png)

**Comment by Made101** [comment] 2021-06-01 14:05
@yaldabaoth444 Hey, They changed the screen and I have this black kinda part on
How do you solve this?
![top](https://user-images.githubusercontent.com/77076813/120336965-826ce600-c310-11eb-8939-d21e930d52aa.png)

**Comment by Made101** [comment] 2021-06-01 14:07
They also changed the game UI a bit.

**Comment by Made101** [comment] 2021-06-01 19:04
Nevermind, I solved that

**Comment by yaldabaoth444** [comment] 2021-06-01 21:45
in what way?

**Comment by Made101** [comment] 2021-06-02 05:00
> in what way?

Nothing significant tbh. People who have devices with a notch got a black screen on the side of notch. The photo above shows that. Because my device has a teardrop notch on the left side, the blackscreen shows on the left side of my phone. The script works just as well now. But I had to install a module through magisk to fix it otherwise the script wouldn't work.
ANd UI changes are nothing significant. I thought the script wouldn't work because of them but it does. So, it's all good :))

**Comment by nujabse** [comment] 2021-06-03 12:07
@made101  Can you provide the name of the magisk module to fix the blackscreen issue for screens with notches? I'm facing the same issue too.

**Comment by Made101** [comment] 2021-06-03 12:15
> @made101 Can you provide the name of the magisk module to fix the blackscreen issue for screens with notches? I'm facing the same issue too.

Search "None display cutout" on Magisk and apply it in the settings after installing
 Settings - Developer option - Display cutout - choose the last option.

**Comment by nujabse** [comment] 2021-06-03 12:18
Thanks a lot, I'll give it a try. BTW, is there any other way to do this on devices that do not have magisk installed (non-root)?

**Comment by Made101** [comment] 2021-06-03 12:19
> Thanks a lot, I'll give it a try. BTW, is there any other way to do this on devices that do not have magisk installed (non-root)?

Dev's said They'll fix it soon, Other than that, I don't think so. You'll have to wait for them to fix it if your device is not rooted.

**Comment by nujabse** [comment] 2021-06-03 12:21
Okay, I may need to do some searches on how to root my device. Thank you!

**Comment by made101** [comment] 2021-06-04 10:15
Hey @yaldabaoth444 A new hunt script is required, can you please look into this? And also I'm giving you my email, can you please give me your discord or something else where can chat about the script you have me earlier privately?

**Closed as completed** 2021-06-04 10:40 UTC
